import { KnowledgeItem } from '../../types';

// Batch 133 (how planes fly / aerodynamics) — a gap. On nexus-4b:
// "what is drag and what are its types" dumped drag-and-drop GUI + drag queen
// definitions; "what is ground effect" answered about psychological grounding
// techniques for anxiety; "coefficient of lift" returned the r-squared
// statistics entry; "flaps and slats" and "how does a propeller work" were
// answered about bird wings and the alula; "why do planes fly so high" said
// "because of the jet stream." Several answers baked in the debunked
// equal-transit-time / "air travels farther over the top so it goes faster"
// explanation of lift.
export const AERODYNAMICS_GAPS: KnowledgeItem[] = [
  {
    id: 'kb-gap-aero-how-planes-fly',
    title: 'How Airplanes Fly (and Why the "Longer Path" Story Is Wrong)',
    category: 'Aviation',
    keywords: [
      'how do airplanes fly how do wings generate lift', 'a wing produces lift by pushing a large mass of air downward newtons third law the equal and opposite reaction is an upward force on the wing at the same time the flow speeds up over the upper surface and its static pressure drops bernoulli so most of the lift shows up as low pressure on top of the wing',
      'these are two descriptions of the same event not competing theories the wing turns the flow the turning requires a pressure gradient the low pressure on top accelerates and bends the air down',
      'the common equal transit time or longer path explanation is wrong air over the top does not have to rejoin air from the bottom and in fact it arrives sooner a flat plate or an upside down wing can still fly at a positive angle of attack the amount of lift depends on angle of attack airspeed squared air density and wing area',
    ],
    content: `An aircraft wing generates lift by deflecting a large mass of air downward. By Newton's third law, pushing that air down produces an equal and opposite upward reaction force on the wing. Simultaneously — and this is the same phenomenon seen a different way — the air accelerates as it curves over the upper surface, and by Bernoulli's principle (and simple conservation of energy) its static pressure drops, so roughly two-thirds of a wing's lift appears as suction on the top surface and one-third as higher pressure pushing up on the bottom. Newton and Bernoulli are not rival theories: the wing turns the airflow, turning a flow requires a pressure difference across it, and that pressure difference is what both accelerates the air and bends it downward. The popular "equal transit time" or "the air has farther to travel over the curved top so it must go faster" explanation is simply incorrect — there is no physical law forcing the air over the top to rejoin the air from the bottom at the trailing edge, and measurements show the upper air actually gets there first. Proof that camber is not the cause: a thin flat plate, a symmetric wing, and even an inverted wing all produce lift when set at a positive angle of attack. The lift force scales as L = ½ρv²·S·C_L — with air density ρ, the square of airspeed v, wing area S, and a lift coefficient C_L that rises with angle of attack until the wing stalls.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-four-forces',
    title: 'The Four Forces of Flight',
    category: 'Aviation',
    keywords: [
      'what are the four forces of flight', 'lift weight thrust and drag the four forces acting on an aircraft in flight',
      'lift acts upward generated by the wings weight acts downward the pull of gravity on the aircrafts mass thrust acts forward from the engines or propeller drag acts backward the air resistance opposing motion',
      'in steady straight and level flight at constant speed the forces are balanced in opposite pairs lift equals weight thrust equals drag if thrust exceeds drag the aircraft accelerates if lift exceeds weight it climbs in a climb or turn the geometry changes and the balance shifts',
    ],
    content: `Four forces act on an aircraft in flight, in two opposing pairs. LIFT acts upward (roughly perpendicular to the flight path), produced mainly by the wings. WEIGHT acts straight down — the force of gravity on the aircraft's total mass, acting through its centre of gravity. THRUST acts forward, produced by the propeller or jet engine(s). DRAG acts backward, the resistance of the air to the aircraft moving through it. In steady, straight, level, unaccelerated flight the pairs are exactly balanced: lift = weight, and thrust = drag. Upsetting a balance changes the motion: more thrust than drag → the aircraft accelerates (and then drag rises with speed until it re-balances); more lift than weight → it climbs; less → it descends. In a climb, part of the weight vector acts along the flight path so thrust must also overcome that component; in a banked turn, lift is tilted so only its vertical component opposes weight, which is why a turning aircraft must increase lift (pull back / add power) to hold altitude. Pilots learn these as the framework for every phase of flight.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-angle-of-attack',
    title: 'Angle of Attack',
    category: 'Aviation',
    keywords: [
      'what is angle of attack aoa', 'the angle between the wings chord line an imaginary straight line from the leading edge to the trailing edge and the relative wind the direction of the oncoming airflow',
      'it is not the same as pitch attitude the nose can point up while the aircraft descends through the air at a high angle of attack raising the angle of attack increases the lift coefficient roughly linearly',
      'until the critical or stalling angle of attack usually around 15 to 18 degrees for a typical wing beyond that the airflow separates from the upper surface lift collapses and the wing stalls a wing always stalls at the same angle of attack regardless of airspeed or attitude',
    ],
    content: `Angle of attack (AoA or alpha) is the angle between the wing's chord line — the straight reference line from the leading edge to the trailing edge — and the relative wind, which is the direction of the air flowing toward the wing (opposite the flight path). It is NOT the same thing as pitch attitude: an aircraft can have its nose above the horizon while sinking through the air at a large angle of attack, or nose-down at a small one. Increasing angle of attack increases the wing's lift coefficient in a nearly straight line — more AoA, more lift — but only up to the "critical" or "stalling" angle of attack, typically about 15–18° for a plain wing. Past that angle the airflow can no longer follow the sharply curved upper surface, it separates into turbulent wake, lift drops sharply, and drag rises: the wing is stalled. A crucial safety point taught to every pilot: a given wing always stalls at the same angle of attack, no matter the airspeed, weight, bank angle, or nose attitude — you can stall at high speed in a steep turn just as easily as slow and level. This is why many aircraft have an AoA indicator or a stall-warning vane that senses angle of attack directly.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-bernoulli',
    title: "Bernoulli's Principle",
    category: 'Physics',
    keywords: [
      'what is bernoullis principle', 'in a steadily flowing fluid where the speed is higher the static pressure is lower and where the speed is lower the pressure is higher it is a statement of conservation of energy along a streamline',
      'the total is the sum of static pressure dynamic pressure from speed and pressure from height it explains why a shower curtain gets sucked inward why two ships passing close are drawn together how a carburettor or an atomiser or a venturi works and part of how a wing works',
      'the principle itself faster flow means lower pressure is correct what is wrong is the equal transit time reason often given for why the air over a wing goes faster air is not required to rejoin at the trailing edge',
    ],
    content: `Bernoulli's principle states that within a steadily flowing fluid, the faster the flow at a point, the lower its static pressure there, and vice versa. It is conservation of energy applied along a streamline: for an ideal incompressible flow, static pressure + dynamic pressure (½ρv², the "pressure" of the motion) + gravitational term (ρgh) stays constant, so if speed goes up, static pressure must come down to keep the sum fixed. Everyday consequences: a shower curtain billows toward you because the moving air inside the shower is at lower pressure; two ships steaming side by side are pulled together; wind over a chimney or a prairie-dog burrow entrance lowers the pressure and draws air out; a Venturi tube, carburettor, atomiser, Bunsen burner, and airspeed indicator (via a pitot-static system) all work on it. It also accounts for part of a wing's lift — the accelerated flow over the upper surface is at reduced pressure. Two cautions: (1) the principle is about speed vs pressure only; it does not by itself say why the air over a wing speeds up. (2) The "equal transit time" story — that air split at the leading edge must meet again at the trailing edge, so the longer upper path forces higher speed — is a myth; the flow is not constrained that way, and the upper air in fact reaches the trailing edge sooner.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-flaps-slats',
    title: 'What Flaps and Slats Do',
    category: 'Aviation',
    keywords: [
      'what do flaps and slats do on an airplane wing', 'these are high lift devices on an aircraft wing not features of a birds wing they let a plane fly safely at the much lower speeds needed for takeoff and landing',
      'flaps extend from the trailing edge rear of the wing and hinge or slide down they increase the wings camber curvature and often its area which raises the lift coefficient at a given speed they also add a lot of drag which helps steepen the approach and slow down',
      'slats extend from the leading edge front of the wing and open a slot that guides high energy air over the top surface re energising the boundary layer this delays airflow separation so the wing can reach a higher angle of attack and lower speed before it stalls together they can roughly double the low speed lift',
    ],
    content: `Flaps and slats are movable "high-lift devices" fitted to an aircraft wing (not parts of a bird's wing). Their job is to let the aircraft generate enough lift to fly safely at the much lower speeds used for takeoff and, especially, landing, so the wing can be sized for efficient high-speed cruise the rest of the time. FLAPS are panels on the trailing (rear) edge that hinge or slide downward and aft when selected. They increase the wing's camber (curvature) and, on more complex types (Fowler flaps), its area as well, which raises the lift coefficient at any given airspeed — so the stall speed drops. Large flap settings also produce a great deal of drag, which is useful on landing: it lets the aircraft fly a steeper, slower, power-on approach without accelerating. SLATS (and fixed leading-edge slots) are panels on the leading (front) edge that move forward to open a carefully shaped gap. Air from below is funnelled through the slot and blown over the top of the wing, adding energy to the slow-moving boundary layer so it stays attached longer. This delays the stall to a higher angle of attack, adding still more usable lift at low speed. With both fully deployed a jet airliner's wing can produce roughly twice the low-speed lift of the clean wing, cutting the approach speed dramatically.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-drag-types',
    title: 'Aerodynamic Drag and Its Types',
    category: 'Aviation',
    keywords: [
      'what is aerodynamic drag and what are its types', 'drag is the force that opposes an aircrafts motion through the air acting backward along the flight path this is aerodynamics not the drag and drop computer gesture or a drag queen',
      'two main families parasitic drag which is everything not related to producing lift and induced drag which is the drag penalty of producing lift parasitic drag splits into form or pressure drag from the shape and wake skin friction drag from air viscosity along the surface and interference drag where airflows from different parts of the aircraft meet',
      'parasitic drag rises with the square of airspeed induced drag falls as speed rises so total drag has a u shape and the bottom of that curve is the speed for best lift to drag ratio near the speed of sound a third type wave drag from shock waves appears',
    ],
    content: `Aerodynamic drag is the force that resists an aircraft's motion through the air, acting backward along the flight path (this is the aviation term, unrelated to the "drag and drop" mouse gesture or to drag performance). It comes in two main families. PARASITIC DRAG is all the drag not associated with making lift, and it has three parts: (1) form (pressure) drag — from the shape of the body and the low-pressure turbulent wake it leaves behind, minimised by streamlining; (2) skin-friction drag — from the air's viscosity dragging along every surface, dependent on surface area and smoothness; (3) interference drag — extra drag created where airflows from different components (wing-fuselage junction, strut fittings) interact, reduced with fairings. INDUCED DRAG (or "drag due to lift") is the unavoidable price of generating lift: the wing throws air downward, which tilts the effective lift vector slightly backward, and it is closely tied to the wingtip vortices. Parasitic drag grows with the square of airspeed, while induced drag is largest at low speed and falls as the aircraft goes faster. Adding them gives a U-shaped total-drag curve; the airspeed at the bottom of the U is where the lift-to-drag ratio is best (max range for a jet, max endurance/glide considerations aside). Approaching the speed of sound, a fourth type — WAVE DRAG, caused by shock waves forming on the aircraft — appears and rises steeply.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-induced-drag',
    title: 'Induced Drag',
    category: 'Aviation',
    keywords: [
      'what is induced drag drag due to lift', 'the component of drag that is created as a by product of generating lift a wing produces lift by deflecting air downward downwash so near the wing the local airflow is angled slightly downward',
      'this tilts the lift force which is perpendicular to the local flow slightly rearward and the rearward component is induced drag it is also described through the wingtip vortices high pressure air below the wing curls around the tip to the low pressure region on top',
      'induced drag is largest at low airspeed and high angle of attack such as takeoff climb and slow flight and it decreases as the aircraft speeds up it is reduced by a higher aspect ratio long slender wing like a glider and by winglets which weaken the tip vortex',
    ],
    content: `Induced drag is the part of an aircraft's drag that exists only because the wing is producing lift — it is "drag due to lift." The mechanism: a lifting wing pushes air downward, so the air leaving the wing has a downward velocity component ("downwash"), and the airflow in the vicinity of the wing is tilted slightly downward from the free-stream direction. The lift force is always perpendicular to the LOCAL airflow, so tilting that flow down tilts the lift vector slightly backward; its small rearward component, in the direction of motion, is induced drag. The same effect can be pictured through the wingtip vortices: the higher-pressure air under the wing spills around each tip into the lower-pressure region on top, rolling up into a trailing vortex that represents wasted energy. Key behaviour: induced drag is greatest at low speed and high angle of attack — during takeoff, initial climb, and slow flight — and it decreases rapidly as airspeed increases (opposite to parasitic drag). It is reduced by using a high-aspect-ratio wing (long and slender, like a sailplane's, which spreads the lift over a longer span and produces weaker tip vortices), by careful spanwise lift distribution (elliptical is ideal), and by adding winglets or raked tips that make it harder for air to curl around the wingtip.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-fly-high',
    title: 'Why Airliners Fly So High',
    category: 'Aviation',
    keywords: [
      'why do planes fly so high at 35000 to 40000 feet', 'the main reason is thin air at altitude the air is much less dense so there is far less parasitic drag the aircraft can fly faster on the same fuel and jet engines are more efficient in the cold thin air',
      'other reasons flying above most weather thunderstorms turbulence icing and clouds are usually below the cruise level a higher glide range and reaction time if a problem occurs clearance above all terrain and separation from slower low altitude traffic',
      'the jet stream is a minor factor and a two edged one airlines route to catch a tailwind and avoid a headwind but it is not why aircraft climb the practical ceiling is set by the engines and by the coffin corner where stall speed and mach limit converge',
    ],
    content: `Airliners cruise at roughly 33,000–42,000 ft for several reinforcing reasons, the biggest being air density. Up there the air is only about a quarter as dense as at sea level, so parasitic drag — which is proportional to air density — is greatly reduced. That lets the aircraft fly at a high true airspeed for a modest fuel flow, and modern turbofan engines are also more thermally efficient in the very cold, thin air. Secondary benefits: (1) it is above almost all significant weather — most thunderstorm tops, turbulence, icing, and cloud are below the cruise level, giving a smoother, safer ride; (2) altitude is energy — from 37,000 ft a jet can glide roughly 100 nautical miles and the crew has many minutes to handle an emergency; (3) guaranteed terrain clearance over mountains; (4) vertical separation from slower general-aviation traffic that stays low. The jet stream is only a minor consideration and cuts both ways: dispatchers plan routes to ride a tailwind and dodge a headwind core, but aircraft do not climb in order to reach it. How high a given flight can go is limited by engine thrust at altitude, by the aircraft's certified ceiling, and by "coffin corner," where the low-speed stall and the high-speed Mach buffet boundaries close together.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-propeller',
    title: 'How a Propeller Works',
    category: 'Aviation',
    keywords: [
      'how does an aircraft propeller work', 'a propeller is a set of rotating wings each blade is an airfoil with a cross section like a wing as the engine spins it the blade moves through the air at an angle of attack and generates an aerodynamic force',
      'that force points mostly forward along the aircrafts axis and is called thrust the reaction is that the blade pushes a column of air backward accelerating the air rearward is the newtonian way to see it',
      'each blade is twisted with a coarse high pitch angle near the hub and a fine low pitch angle at the tip because the tip travels much faster than the root so the twist keeps the angle of attack roughly constant along the blade constant speed propellers change the whole blade pitch in flight to stay efficient at different speeds',
    ],
    content: `A propeller is simply a set of rotating wings. Each blade has an airfoil cross-section, just like a wing, and is set at an angle to the plane of rotation. When the engine spins the propeller, every blade moves through the air along a helical path at an angle of attack, and — exactly like a wing — it generates an aerodynamic force perpendicular to its motion. Because the blade's motion is mostly around the hub, that aerodynamic force points mostly forward along the aircraft's centreline: this forward force is thrust. Equivalently (Newton's third law), the propeller accelerates a large column of air rearward, and the reaction drives the aircraft forward. Two design details: (1) The blades are twisted — a coarse (steep) pitch angle near the hub and a fine (shallow) angle toward the tip. This is because the tip, being farther out, travels through a much greater distance per revolution and therefore meets the air at a higher resultant speed and shallower helix angle than the root; the built-in twist keeps the angle of attack roughly uniform along the whole blade so all of it works efficiently. (2) A fixed-pitch propeller is a compromise, efficient at only one speed. A constant-speed (variable-pitch) propeller uses a governor to rotate the blades to a coarser pitch as the aircraft speeds up (like an automatic gearbox), holding the engine at its best RPM and keeping the blade angle of attack near optimum across the flight envelope. Feathering turns the blades edge-on to stop drag after an engine failure.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-ground-effect',
    title: 'Ground Effect (Aerodynamics)',
    category: 'Aviation',
    keywords: [
      'what is ground effect in aviation', 'the increase in lift and decrease in induced drag that a wing experiences when it flies within about one wingspan of the ground or water this is an aerodynamic effect not a psychological grounding technique for anxiety',
      'close to the surface the ground interferes with the downwash and stops the wingtip vortices from fully developing so less of the flow is deflected downward this cuts induced drag sometimes by 30 to 50 percent right at the surface and makes the wing more efficient',
      'pilots feel it in the landing flare the aircraft floats and is reluctant to touch down and on takeoff an aircraft can lift off in ground effect then struggle to climb out of it ekranoplans and the wing in ground effect craft are designed to cruise permanently in it',
    ],
    content: `Ground effect is the aerodynamic phenomenon in which a wing becomes more efficient — more lift, much less induced drag — when it flies very close to the ground or water, within roughly one wingspan of the surface and strongest within about half a wingspan. (It has nothing to do with the "grounding" techniques used for anxiety.) The cause: normally a lifting wing produces a broad sheet of downwash and strong wingtip vortices. Near the surface, the ground physically obstructs the downward flow and prevents the tip vortices from spiralling up and inboard, so the local airflow is deflected downward much less than usual. Since induced drag comes from that downwash-induced backward tilt of the lift vector, blocking the downwash can cut induced drag by 30–50% right at the surface, and the effective angle of attack for a given lift is reduced. Pilots experience it directly: in the landing flare the aircraft "floats" down the runway and resists settling onto the wheels; on takeoff a heavy or underpowered aircraft may become airborne while still in ground effect and then be unable to climb away once it rises out of it (a classic accident scenario on a hot day). Ekranoplans and other "wing-in-ground-effect" vehicles (the Soviet "Caspian Sea Monster") are built to cruise permanently a few metres above the water to exploit the efficiency gain.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-turning',
    title: 'How an Airplane Turns',
    category: 'Aviation',
    keywords: [
      'how does an airplane turn', 'an aircraft turns by banking rolling to one side so that the lift force which always acts perpendicular to the wings is tilted the horizontal component of the tilted lift acts sideways and pulls the aircraft around the turn',
      'the pilot rolls into the bank with the ailerons then because the banked lift now has a smaller vertical component they must pull back slightly on the elevator to increase total lift and hold altitude the rudder is used to coordinate the turn cancelling the adverse yaw from the ailerons so the aircraft is not slipping or skidding',
      'the rudder alone does not turn the aircraft it just points the nose it is a bank and pull manoeuvre not a car like steering steeper bank means a tighter faster turn but more load factor g and a higher stall speed',
    ],
    content: `An airplane turns by banking, not by steering like a car or a boat. The wings' lift always acts perpendicular to the wings, so when the aircraft rolls to one side, the lift vector tilts with it. That tilted lift now has two components: a vertical one that still opposes weight, and a horizontal one pointing into the turn. The horizontal component is the centripetal force that pulls the aircraft around the curve. The full technique: (1) the pilot uses the AILERONS to roll into the desired bank angle; (2) because the banked lift has a reduced vertical component, the pilot adds a little back-pressure on the ELEVATOR to increase total lift and keep the vertical component equal to weight, otherwise the nose drops and the aircraft descends and its speed builds; (3) the pilot uses the RUDDER to "coordinate" — the down-going aileron creates extra drag on the outside wing ("adverse yaw") that would swing the nose the wrong way, and rudder input cancels it so the aircraft flies cleanly through the turn without slipping or skidding (the "ball" stays centred). A steeper bank gives a tighter, quicker turn but multiplies the load factor (g) and raises the stall speed — at 60° of bank the wings carry 2g and the stall speed is 41% higher.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-cl',
    title: 'Coefficient of Lift',
    category: 'Aviation',
    keywords: [
      'what is the coefficient of lift cl', 'a dimensionless number that captures how much lift a particular airfoil or wing produces for its size at a given angle of attack independent of how big it is or how fast or dense the air is this is aerodynamics not the r squared statistic',
      'it appears in the lift equation lift equals one half times air density times velocity squared times wing area times the lift coefficient so cl bundles together the effects of airfoil shape and angle of attack',
      'for a typical wing cl increases almost linearly with angle of attack from a small value maybe 0.2 at zero degrees up to a maximum cl max around 1.5 for a plain wing or 2.5 to 3 with flaps and slats deployed just before the stall past the stalling angle cl drops sharply',
    ],
    content: `The coefficient of lift (C_L, or C_l for a 2-D airfoil section) is a dimensionless number that expresses how effective a given airfoil or wing is at producing lift, stripped of the effects of size, speed, and air density. (It is an aerodynamic quantity and has nothing to do with r² or the "coefficient of determination" in statistics.) It is defined by the lift equation: L = ½ · ρ · v² · S · C_L, where ρ is air density, v airspeed, and S wing area — so C_L is what remains once you divide out the dynamic pressure and the wing area. Physically, C_L captures the combined influence of the airfoil's shape (camber, thickness) and its current angle of attack. For a typical wing, C_L rises almost linearly with angle of attack: from perhaps 0.1–0.3 at zero angle of attack up to a maximum, C_L,max, of about 1.5 for a plain wing — or 2.5–3.0 with flaps and slats extended — reached just below the stalling angle of attack. Beyond the critical angle the flow separates and C_L falls off steeply. Designers plot C_L against angle of attack (the "lift curve"), and against drag coefficient C_D (the "drag polar"), to characterise a wing. Because required lift equals weight, an aircraft flies each speed at whatever C_L balances the equation — high C_L (high angle of attack) when slow, low C_L when fast.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-gap-aero-swept-wings',
    title: 'Why Jet Airplane Wings Are Swept Back',
    category: 'Aviation',
    keywords: [
      'why are airplane wings swept back swept wing', 'wing sweep angling the wings rearward from the root delays the drag rise that occurs as the aircraft approaches the speed of sound',
      'only the component of the airflow perpendicular to the wing leading edge matters for forming shock waves so sweeping the wing back makes it behave as if it is flying at a lower mach number letting the aircraft cruise efficiently at mach 0.78 to 0.90 without a big wave drag penalty',
      'downsides swept wings produce less lift at low speed so higher takeoff and landing speeds and need bigger flaps they tend to stall at the tips first which can pitch the nose up and they flex and twist more straight wings are better for slow aircraft forward swept and variable sweep are rarer solutions',
    ],
    content: `Sweeping the wings rearward (or, rarely, forward) is done to postpone the sharp rise in drag that happens as an aircraft nears the speed of sound. As airflow accelerates over a wing, it can reach Mach 1 locally even while the aircraft itself is still subsonic (around Mach 0.75+); shock waves then form on the wing and cause "wave drag," which climbs steeply. The key idea behind sweep: only the component of the airflow measured perpendicular to the wing's leading edge governs the pressure distribution and shock formation — the spanwise component does little. Angling the wing back by, say, 35° means that perpendicular component corresponds to a lower effective Mach number, so shocks and their drag are delayed to a higher flight speed. This lets jet airliners cruise efficiently at Mach 0.78–0.90. The trade-offs are why slow aircraft keep straight wings: a swept wing generates less lift for a given angle of attack, so takeoff and landing speeds are higher and more elaborate high-lift devices are needed; the spanwise flow encourages the wingtips to stall first, which can cause an uncommanded nose-up pitch (countered with wing fences, vortilons, and washout); and swept wings twist and flex more, raising structural and flutter concerns. Variable-sweep ("swing") wings and forward sweep are niche answers to the same problem.`,
    createdAt: Date.now(),
  },
];
