import { KnowledgeItem } from '../../types';

export const RENEWABLE_ENERGY_TYPES_DEEP_CORPUS: KnowledgeItem[] = [
  {
    id: 'kb-energy-geothermal-hydro',
    title: 'Geothermal and Hydroelectric Power Explained',
    category: 'Environment',
    keywords: ['how does geothermal energy work', 'how does hydroelectric power work', 'geothermal power plant', 'dam electricity generation'],
    content: `**Geothermal energy** harnesses heat from deep within the Earth itself, which stays hot due to the planet's molten core and the slow decay of radioactive elements in its crust. Geothermal power plants typically drill wells into underground reservoirs of naturally heated water or steam, bringing it to the surface to spin turbines connected to electricity generators, then often reinjecting the cooled water back underground to sustain the resource. Iceland, sitting atop intense volcanic and tectonic activity, generates a remarkably large share of its electricity and home heating from geothermal sources, and the technology is especially practical in geologically active regions worldwide (like parts of the western U.S., the Philippines, and Indonesia). **Hydroelectric power**, one of the oldest and most widely used forms of renewable energy, generates electricity by using flowing or falling water to spin turbines — most commonly by building a dam across a river to create a reservoir, then releasing controlled amounts of water through the dam to drive generators, though "run-of-river" systems without large reservoirs also exist. Hydroelectric dams can provide highly reliable, controllable power output (unlike weather-dependent solar or wind) and often reservoirs additionally serve for flood control, irrigation, and recreation — but large dam projects can also cause significant environmental disruption, including flooding vast areas of land, displacing local communities, and altering river ecosystems and fish migration patterns, making them more environmentally contested than typically assumed for a "green" energy source.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-energy-biomass-nuclear-context',
    title: 'Biomass Energy and How It Compares to Fossil Fuels',
    category: 'Environment',
    keywords: ['what is biomass energy', 'biomass vs fossil fuels', 'burning wood for energy renewable', 'biofuel ethanol'],
    content: `**Biomass energy** is generated by burning or otherwise converting organic material — wood, agricultural waste, dedicated energy crops, or even certain types of waste — into usable heat, electricity, or fuel (biofuels like ethanol, commonly blended into gasoline, are one major biomass-derived product). Biomass is generally classified as renewable because the plant material used can, in principle, be regrown relatively quickly (over years rather than the millions of years required to form fossil fuels like coal and oil), and because growing plants absorb carbon dioxide from the atmosphere as they grow, theoretically offsetting at least some of the carbon released when the biomass is later burned. However, biomass energy's actual environmental benefit is more debated and complicated than it might first appear: burning biomass still releases carbon dioxide and other pollutants directly at the point of combustion (similar to burning fossil fuels), the climate benefit depends heavily on how quickly and sustainably the biomass is regrown and whether the harvesting process itself causes deforestation or habitat loss, and large-scale energy-crop farming can compete with food production for available agricultural land. Compared to fossil fuels, biomass and other renewables like solar, wind, geothermal, and hydro don't add long-buried ancient carbon back into the atmosphere the way burning coal, oil, or natural gas does — a critical distinction, since fossil fuel combustion is the dominant driver of the excess atmospheric carbon dioxide behind modern human-caused climate change.`,
    createdAt: Date.now(),
  },
];
