import { KnowledgeItem } from '../../types';

export const SPACE_MISSIONS_AND_AGENCIES_CORPUS: KnowledgeItem[] = [
  {
    id: 'kb-space-apollo11',
    title: 'Apollo 11: The First Moon Landing',
    category: 'Astronomy',
    keywords: ['apollo 11 mission', 'first moon landing', 'neil armstrong buzz aldrin', 'apollo 11 date july 1969'],
    content: `**Apollo 11** was the NASA mission that achieved the first crewed Moon landing, launching on July 16, 1969, and landing the Lunar Module "Eagle" in the Moon's Sea of Tranquility on July 20, 1969. Astronaut **Neil Armstrong** became the first human to step onto the lunar surface, famously radioing "That's one small step for man, one giant leap for mankind," followed shortly after by **Buzz Aldrin**; a third crew member, **Michael Collins**, remained in lunar orbit piloting the command module, without which the mission couldn't have returned home. The astronauts spent about two and a half hours outside the lander, collecting roughly 21.5 kilograms (47.5 pounds) of lunar rock and soil samples, planting a U.S. flag, and leaving a plaque reading "We came in peace for all mankind." The mission fulfilled a goal President John F. Kennedy had set in a famous 1961 speech, committing the U.S. to landing a man on the Moon before the decade was out — a direct response to Cold War-era competitive pressure after the Soviet Union had beaten the U.S. to several earlier space milestones, including the first satellite (Sputnik, 1957) and first human in space (Yuri Gagarin, 1961). Apollo 11 was followed by five more successful crewed Moon landings through Apollo 17 in 1972, and no human has returned to the lunar surface since, though NASA's Artemis program aims to send astronauts back in the coming years.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-space-iss',
    title: 'The International Space Station',
    category: 'Astronomy',
    keywords: ['what is the international space station', 'iss facts', 'how many countries built the iss', 'iss orbit altitude'],
    content: `The **International Space Station (ISS)** is a large, habitable satellite orbiting roughly 400 kilometers (250 miles) above Earth, functioning as a continuously crewed orbital laboratory for scientific research in microgravity conditions unavailable on Earth. It's a collaborative project among five participating space agencies — NASA (United States), Roscosmos (Russia), ESA (Europe), JAXA (Japan), and CSA (Canada) — with construction beginning in 1998 and the station continuously crewed by rotating international astronaut teams since November 2000, making it one of the longest continuous human presences beyond Earth in history. The ISS orbits Earth roughly every 90 minutes, meaning its crew experiences about 16 sunrises and sunsets each day, and it travels at approximately 28,000 km/h (17,500 mph). Research conducted aboard covers fields including human physiology (studying how extended weightlessness affects bones, muscles, and the cardiovascular system, crucial for planning future long-duration missions to Mars), materials science, biology, and Earth observation. The station is expected to be retired sometime in the later 2020s or early 2030s, with plans for a controlled deorbit into a remote area of the Pacific Ocean, while commercial and government-led successor stations are already in development, including projects from companies like Axiom Space intended to take over crewed low-Earth-orbit research.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-space-voyager-and-esa',
    title: 'The Voyager Probes and the European Space Agency',
    category: 'Astronomy',
    keywords: ['what did the voyager probes discover', 'voyager 1 voyager 2 interstellar space', 'what is the european space agency', 'esa vs nasa'],
    content: `**Voyager 1 and Voyager 2** are NASA robotic probes launched in 1977 to take advantage of a rare planetary alignment allowing a single mission to visit multiple outer planets using gravitational assists. They returned groundbreaking close-up data and imagery of Jupiter, Saturn, Uranus, and Neptune (Voyager 2 remains the only spacecraft to have ever visited Uranus and Neptune up close), discovering active volcanoes on Jupiter's moon Io, evidence of a subsurface ocean on Saturn's moon Enceladus, and numerous previously unknown moons and ring details. Both probes are still operating today, having become the most distant human-made objects from Earth — Voyager 1 crossed into **interstellar space** (beyond the heliosphere, the bubble of particles and magnetic field generated by our Sun) in 2012, followed by Voyager 2 in 2018, making them the first human-made objects to leave the Sun's direct influence, though they'll take tens of thousands of years to approach another star system. Each carries a "Golden Record" containing sounds, images, and music representing life and culture on Earth, intended for any potential intelligent extraterrestrial life that might one day encounter it. The **European Space Agency (ESA)**, founded in 1975 and headquartered in Paris, is Europe's counterpart to NASA, a multinational agency (currently 22+ member states) responsible for missions including the Rosetta comet-lander mission, the Gaia star-mapping telescope, and major collaborative contributions to projects like the James Webb Space Telescope alongside NASA and the Canadian Space Agency.`,
    createdAt: Date.now(),
  },
  {
    id: 'kb-space-spacex',
    title: 'SpaceX: Reusable Rockets and Commercial Spaceflight',
    category: 'Astronomy',
    keywords: ['what is spacex known for', 'spacex reusable rockets', 'elon musk spacex', 'falcon 9 starship'],
    content: `**SpaceX** (Space Exploration Technologies Corp.), founded by Elon Musk in 2002, is a private aerospace company best known for pioneering **reusable orbital rockets** — a major cost-saving innovation, since traditional rockets historically were single-use and discarded (or destroyed) after each launch, similar to throwing away an airplane after one flight. SpaceX's Falcon 9 rocket routinely lands its first-stage booster back on Earth (either on a ground pad or a floating "drone ship" at sea) after launch, allowing it to be refurbished and reused for future missions, dramatically reducing launch costs compared to earlier, fully expendable rockets. SpaceX became the first private company to send astronauts to the International Space Station, launching NASA crews aboard its Crew Dragon capsule starting in 2020, ending nearly a decade of U.S. reliance on Russian Soyuz rockets for crewed ISS access following the retirement of NASA's Space Shuttle program in 2011. SpaceX also operates the Starlink satellite internet constellation, providing broadband internet access via thousands of small satellites in low Earth orbit, and is developing **Starship**, an enormous fully reusable next-generation rocket system intended to eventually support ambitious goals including crewed missions to the Moon (under NASA's Artemis program) and, longer-term, Mars.`,
    createdAt: Date.now(),
  },
];
